rdisc_srv,Makefile: Fix build.
With "make rdisc_src.o", we got
| rdisc.c: In function 'pr_pack':
| rdisc.c:889:17: error: incompatible types when assigning to type 'struct in_addr' from type 'u_int32_t'
| rdisc.c: In function 'finish':
| rdisc.c:959:7: warning: unused variable 'i' [-Wunused-variable]

With "make rdisc_srv", we got many multiple definition errors because -c was
missing to make rdisc_srv.o.

Signed-off-by: YOSHIFUJI Hideaki <yoshfuji@linux-ipv6.org>