CI: Temporarily remove Tumbleweed
Due another docker issue - blocks clone3 syscall any distro using glibc
2.34 is unusable on GitHub Actions. That's what happened to openSUSE
Tumbleweed [1] (the first distro as Fedora 35 has not been released
yet).

In openSUSE job this issue causes zypper to abort => we cannot install
packages:

+ zypper --non-interactive install --no-recommends clang docbook_5
  docbook5-xsl-stylesheets gcc gettext-tools iproute2 libcap-devel
  libcap-progs libidn2-devel libxslt-tools make meson ninja pkg-config
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
./ci/opensuse.sh: line 19:    23 Aborted                 (core dumped)
zypper --non-interactive install --no-recommends clang docbook_5
docbook5-xsl-stylesheets gcc gettext-tools iproute2 libcap-devel
libcap-progs libidn2-devel libxslt-tools make meson ninja pkg-config
Error: Process completed with exit code 134.

[1] https://bugzilla.opensuse.org/show_bug.cgi?id=1190670
[2] https://github.com/pevik/iputils/runs/3685689878

Signed-off-by: Petr Vorel <pvorel@suse.cz>