traceroute6: add missing #include <inttypes.h>
This fixes:
  traceroute6.c:623:21: error: expected ')'
                if (fscanf(f, "%" SCNu16, &nr) != 1)
                                  ^
  traceroute6.c:623:13: note: to match this '('
                if (fscanf(f, "%" SCNu16, &nr) != 1)
                            ^

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I1ba9d81ce9a571a917322c2628b426dd6a01d7c4