ping6_common.c: 3x fix missing rts-> on flowlabel
This fixes:
  ping/ping6_common.c:353:27: error: use of undeclared identifier 'flowlabel'
                freq->flr_label = htonl(flowlabel & IPV6_FLOWINFO_FLOWLABEL);
                                        ^
  ping/ping6_common.c:360:3: error: use of undeclared identifier 'flowlabel'
                flowlabel = freq->flr_label;
                ^
  ping/ping6_common.c:366:33: error: use of undeclared identifier 'flowlabel'
                rts->whereto6.sin6_flowinfo = flowlabel;
                                              ^

Obvious mistake while switching to using the 'rts' structure.
(triggering it requires IPV6_FLOWLABEL_MGR and IPV6_FLOWINFO_SEND to be defined)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I6950490a94ea08ec0ff93f317224c47521984483