tracepath: Fix missing end tag for OPTION.
Fix doc/man compilation error: end tag for "OPTION" omitted, but its declaration does not permit this

Signed-off-by: YOSHIFUJI Hideaki <hideaki.yoshifuji@miraclelinux.com>